version: "3.8"
services:
  postgresql:
    image: postgres:12.1-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_d:/var/lib/postgresql/data
    networks:
      - api

  app:
    build:
      context: .
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - postgresql
    volumes:
      - ".:/var/www/dockerized-rails-api"
    networks:
      - api

volumes:
  postgres_d:

networks:
  api:
    driver: "bridge"
