default: &default
  adapter:  postgresql
  host:     <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  port:     <%= ENV['POSTGRES_PORT'] || 5432 %>
  pool:     <%= ENV['POSTGRES_POOL'] || 5 %>
  encoding: unicode
  username: <%= ENV['POSTGRES_USERNAME'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'postgres' %>
  sslmode: disable

development:
  <<: *default
  database: dockerized_rails_api_dev

test:
  <<: *default
  database: dockerized_rails_api_test

production:
  url: <%= ENV['DATABASE_URL'] %>
